apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-service-deployment
  labels:
    app: openai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-service
  template:
    metadata:
      labels:
        app: openai-service
    spec:
      containers:
      - name: openai-service
        image: sobrian.azurecr.io/openai-service
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: openai-service-service
spec:
  selector:
    app: openai-service
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000