apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-service-deployment
  labels:
    app: openai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-service
  template:
    metadata:
      labels:
        app: openai-service
    spec:
      containers:
      - name: openai-service
        image: sobrian.azurecr.io/openai-service
        ports:
        - containerPort: 3000
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: openai-service-secret
              key: openai-service-azure-client-id
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: openai-service-secret
              key: openai-service-azure-tenant-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openai-service-secret
              key: openai-service-azure-client-secret

---

apiVersion: v1
kind: Service
metadata:
  name: openai-service-service
spec:
  selector:
    app: openai-service
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000